In [2]:
MyDict={"Name":"Jack", "Last Name":"Mccay", "year": 1964}
MyDict
variable=MyDict["Name"]
print(variable)   #it returns the value of the key "Name" which is 'Jack'

Jack


Loops

In [3]:
range(100)

range(0, 100)

In [4]:
for x in range(100):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [6]:
for number in range(2, 100, 20):
    print(number)

2
22
42
62
82


In [7]:
MyDict={"Name":"Jack", "Last Name":"Mccay", "year": 1964}
MyDict

{'Name': 'Jack', 'Last Name': 'Mccay', 'year': 1964}

In [8]:
MyDict['year']=2019   #changing the value of the key "year"
MyDict

{'Name': 'Jack', 'Last Name': 'Mccay', 'year': 2019}

In [9]:
MyDict.keys()

dict_keys(['Name', 'Last Name', 'year'])

In [10]:
MyDict.values()

dict_values(['Jack', 'Mccay', 2019])

In [11]:
MyDict.items()

dict_items([('Name', 'Jack'), ('Last Name', 'Mccay'), ('year', 2019)])

In [12]:
dict()

{}

In [18]:
Dict_items()

NameError: name 'Dict_items' is not defined

In [14]:
keys()

NameError: name 'keys' is not defined

In [21]:
i=3
while i<10:
    print(i)
    i +=2

3
5
7
9


In [24]:
MyDict={"Name":"Jack", "Last Name":"Mccay", "year": 2019}
MyDict['Survived']='Yes'   #adding new element (new key and new value)
MyDict   #it returns the new dictionary: {'Last Name': 'Mccay', 'Name': 'Jack', 'Survived': 'Yes', 'year': 2019}

{'Name': 'Jack', 'Last Name': 'Mccay', 'year': 2019, 'Survived': 'Yes'}

In [25]:
for x in range(2, 10, 30):
    print(x)

2


In [26]:
def my_function():
    print("Hello from a function")
my_function()

Hello from a function


In [27]:
def my_function(parameter):
    print("I want to learn "+parameter)
my_function("to code!")
my_function("to do AI!")

I want to learn to code!
I want to learn to do AI!


In [28]:
def my_function(first_parameter, second_parameter):
    print("First parameter: "+first_parameter)
    print("Second parameter: "+second_parameter)
my_function("Hey", "you!")

First parameter: Hey
Second parameter: you!


In [29]:
def my_function(country="Tunisia"):
    print("I am from "+country)
my_function("Maroc")
my_function("Algeria")
my_function()

I am from Maroc
I am from Algeria
I am from Tunisia


In [31]:
def my_function(x):
    return 6*x
print(my_function(0))
print(my_function(1))
print(my_function(2))

0
6
12


In [32]:
sum = lambda a,b,c : a+b+c
print(sum(2,6,3)) #11

11


In [35]:
year = lambda ch : ch[:4]
ch = "20200310"
print(year(ch)) #2020

2020


In [36]:
test = lambda date : date.split('/')[1]
date = '2020/03/10'
print(test(date))

03


In [40]:
test = lambda date : date.split('/')[1]
date = '2020/03/10'
print(test(date))


03


In [41]:
date.split('/')

['2020', '03', '10']

In [43]:
tuple1 = [1,2,3]
tuple2 = (4,5,6)

it = lambda a,b: a+b
result =list(map(it, tuple1, tuple2))

result

[5, 7, 9]

import numpy

In [44]:
import numpy

In [46]:
import numpy as np

In [58]:
new_array=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
new_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [52]:
import scipy as sci

In [51]:
import cryptography as cry

In [54]:
tab1 = np.array([[ 1, 2, 3, 4], [ 5, 6, 7, 8], [ 9, 10, 11, 12]])
tab1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [89]:
tab1[2,2]

11

In [55]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [56]:
print(tab1.shape)

(3, 4)


In [59]:
print(new_array.shape)

(4, 3)


In [60]:
print(type(new_array))

<class 'numpy.ndarray'>


In [63]:
print(new_array[0,0], new_array[0,1])

1 2


In [68]:
print(tab1[0,0], tab1[0,1])

1 2


In [71]:
value = np.random.random()
print(value)

0.21914459652131368


In [78]:
arrays = np.random.random((4,3))
print(arrays)

[[0.31199946 0.54762585 0.16431477]
 [0.04185602 0.32853033 0.91325864]
 [0.39736223 0.33350423 0.23780303]
 [0.12858944 0.53058591 0.45926511]]


In [91]:
array = np.random.randint(2,50, size=(5,8))
array

array([[37, 23,  8, 19, 42,  9, 18, 35],
       [13,  4,  2, 48, 31, 14, 12, 13],
       [30, 38, 27, 30, 42, 25,  5, 27],
       [43, 30,  5, 18, 26, 47, 11, 38],
       [15, 31, 42, 39, 24, 32, 33, 44]])

In [80]:
star = np.zeros(4)
print(star)

[0. 0. 0. 0.]


In [82]:
stop = np.eye(5)
stop

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [83]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
print(x)

[[1. 2.]
 [3. 4.]]


In [84]:
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(y)

[[5. 6.]
 [7. 8.]]


In [85]:
print(x + y)

[[ 6.  8.]
 [10. 12.]]


In [96]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
bool_idx = (a < 2)
print(bool_idx)
print(a[bool_idx])
print([a < 2])

[[ True False False]
 [False False False]
 [False False False]]
[1]
[array([[ True, False, False],
       [False, False, False],
       [False, False, False]])]


In [97]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(a)
bool_idx = (a > 2)
print(bool_idx)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False  True]
 [ True  True  True]
 [ True  True  True]]
